### ISSUE TITLE
Not working in blender 3.3.1

### ISSUE THREAD

**Issue by Alexxkrehmen** [Franck-Demongin/NX_Picker#1]
Hi,

The panel is empty on blender 3.3.1

![image](https://user-images.githubusercontent.com/12670889/195922572-8937a566-e0f5-4a8d-84c7-c491281954f2.png)

**Comment by Alexxkrehmen** [comment]
Woops ! My bad... I tried it in th UV editor, Not the Image Editor.
By the way, It could be useful to make it available in the Texture Editor too ;)

**Comment by Franck-Demongin** [comment]
Thank you for your comment! Yes, there are a few places where this could be useful. Vertex paint for example... I started a new version with several updates (the possibility of exporting the palette in ACO format for example) and if I can I would try to have some options in the preferences to let the user choose where to display the picker tool.
